// Branding for generated documents (PDF exports, PO forms). Kept as a tiny
// module-level registry rather than React context because the PDF builders
// are plain functions called from ~25 screens; BrandingProvider pushes the
// current values here whenever they change. Import-safe in tests: defaults
// apply until something calls setPdfBranding().

export interface PdfBranding {
  platformName: string;
  primaryColor: string; // #RRGGBB
  supportEmail: string;
}

let current: PdfBranding = { platformName: 'VestaPortal', primaryColor: '#123B44', supportEmail: '' };

export function setPdfBranding(next: Partial<PdfBranding>) {
  current = { ...current, ...next };
}

export function getPdfBranding(): PdfBranding {
  return current;
}

// jsPDF / jspdf-autotable want RGB tuples.
export function primaryRgb(): [number, number, number] {
  const m = /^#?([0-9a-f]{6})$/i.exec(current.primaryColor);
  const n = parseInt(m ? m[1] : '123B44', 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

// Footer line shared by every generated document.
export function documentFooter(when: Date = new Date()): string {
  const parts = [`Generated by ${current.platformName}`, when.toLocaleString()];
  if (current.supportEmail) parts.push(current.supportEmail);
  return parts.join(' · ');
}
